io:
  # Sawyer SDK Controllers: Gripper --------------------------
  right_gripper_controller:
    type: aml_sawyer_sim_controllers/SawyerGripperController
    topic: /io/end_effector/right_gripper/command
    properties: /io/end_effector/right_gripper/config
    joints:
      r_gripper_l_finger_controller:
        joint: r_gripper_l_finger_joint
        pid: {p: 1000,  i: 0.1, d: 0.01}
      r_gripper_r_finger_controller:
        joint: r_gripper_r_finger_joint
        pid: {p: 1000,  i: 0.1, d: 0.01}
