all:
	g++ -O2 -I../../include/pisa_soft_hand/ test_pisa_hand.cpp -I../../src/pisa_soft_hand/ -std=c++11 -o ./bin/test_pisa_hand

run: all
	/home/mjm/catkin_workspaces/baxter_ws/src/aml/aml_drivers/tests/pisa_soft_hand/bin/test_pisa_hand
